project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Shihang Liu"
  site-url: https://sehighs.github.io
  favicon: images/bhb.JPG
  repo-url: https://github.com/sehighs/sehighs.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      ABA BBQ!
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "About"
        href: index.qmd
      - text: "Works"
        href: publications.qmd
      - text: "Notes"
        href: Notes.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细